#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
# used to link nvm to the script | might not work on windows
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

nvm use && yarn lint
